import Head from 'next/head';
import Link from 'next/link';
import styles from '@/styles/Home.module.css';
import utilStyles from '@/styles/utils.module.scss';
import { routeNames } from '../../routes';
import { dAppName } from 'config';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
         <h1>{ dAppName }</h1>
         <button className={utilStyles.loginBtn}>
              <Link href={routeNames.unlock}>Login</Link>
         </button>
         
      </main>
    </>
  )
};
